services:
  api:
    container_name: delivery-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - delivery-network

networks:
  delivery-network: