services:
  api:
    container_name: delivery-api-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:3000"
    env_file:
      - .env
    restart: always
    networks:
      - delivery-network

networks:
  delivery-network:
    external: true
